version: '3.9'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/keycloak/data:/var/lib/postgresql
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    command: start-dev
    volumes:
      - ../volumes/keycloak/keycloak:/opt/keycloak/data

networks:
  keycloak-network:
    driver: bridge
