version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    # volumes:
    #   - ../volumes/mysql-data:/var/lib/mysql
